### PR TITLE
fix: Load of components for views

### LINKED ISSUE #8: Missing value on relationship and index
On form, the value is correctly selected in the dropdown based on the dependsOn field.
Capture d’écran, le 2022-10-11 à 11 43 55

But on relationship view, the column is empty.
Capture d’écran, le 2022-10-11 à 11 44 01

### PR DESCRIPTION
**Pull request by joserick**
fix: [Missing value on relationship and index](https://github.com/webparking/nova-belongs-to-dependency/issues/8) #8

### CODE REVIEW

**Comment by RVxLab** [comment]
I don’t see any issues with this from a static analysis perspective. 

@dgerrese could you verify this is working as expected?

**Comment by mrleblanc101** [comment]
Wow haha, nice catch.
Although, why do you use `require().default` instead of `import` ?

**Comment by joserick** [comment]
Hi @mrleblanc101 

It is that "require" is a NodeJS function and it is needed since the file is read by it, on the other hand the "import" is more of a  syntax (ES6) for javascript.

Update the "Minified" by anything:

Captura desde 2023-02-14 23-59-52

**Comment by mrleblanc101** [comment]
@joserick You can use ES import in node since version 12. Also there is Webpack so it doesn't matter as it will be bundled. ES import should be the default nowadays.

**Comment by joserick** [comment]
@mrleblanc101 So in that case it would look like this: [cd8bce8](https://github.com/webparking/nova-belongs-to-dependency/pull/9/commits/cd8bce8684df6fd657c1be825cd269b60aceaa23)

**Comment by dgerrese** [comment]
Looks good to me.

**Comment by joserick** [comment]
@dgerrese Thanks in advance, just to request the new release (Tag) to be able to update with compose.

**Pull request merged**
